#JDBC Configutation for Database Connection
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://database-2.cenwio6akcpr.us-east-1.rds.amazonaws.com:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
jdbc.username=admin
jdbc.password=Admin12345

#Memcached Configuration For Active and StandBy Host
#For Active Host
# Memcached Active
memcached.active.host=mc01-ukc93e.serverless.use1.cache.amazonaws.com
memcached.active.port=11211

# Memcached StandBy
memcached.standBy.host=mc01-ukc93e-serverless.use1.cache.amazonaws.com
memcached.standBy.port=11211

#RabbitMq Configuration
rabbitmq.address=b-250e5b7c-bab5-4577-b45f-6662f9edf9a9.mq.us-east-1.on.aws
rabbitmq.port=5671
rabbitmq.username=test
rabbitmq.password=test12345678
rabbitmq.ssl=true



#Elasticesearch Configuration
elasticsearch.host =vprosearch01
elasticsearch.port =9300
elasticsearch.cluster=vprofile
elasticsearch.node=vprofilenode
